baseurl = "http://www.example.com"
title = "chaitanya"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
    author = "Chaitanya"
    info = "Full Stack DevOps/JAMStack enthusiast/ =Game developer"
    description = "Chaitanya portfolio"
    keywords = "Game developer,personal"
    avatarurl = "images/pp.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "This hyaku-nigiri is evolving."

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/Chaitanyassr"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/Chinu282828777"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
